name: CI
on:
  pull_request:
    branches: [ main, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 23]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run typecheck
      - run: npm run lint

      # usar cobertura en CI
      - run: npm run test:ci
      # subir cobertura
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-${{ matrix.node-version }}
          path: coverage
      # subir reporte JUnit (requiere jest-junit y config en jest.config.mjs)
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jest-junit-${{ matrix.node-version }}
          path: reports/jest-junit.xml

